### ISSUE TITLE
create sponsorship fund endpoints

### ISSUE THREAD

**Issue by victorzheng02** [WATonomous/wato_finance_system#1]
1. Create the create sponsorship fund endpoint at POST `/sponsorshipfunds` 
The post request body should match the schema of SponsorshipFund.model.js

2. Create the get all sponsorship fund endpoint at GET `/sponsorshipfunds`
The get should have no query parameters and return all the sponsorship funds

3. Create the edit sponsorship fund endpoint at PUT `/sponsorshipfunds/:id`
The put request body should match the schema of SponsorshipFund.model.js with all fields optional. It should add or update any fields specified in the request body. All fields not specified in the request body should be touched.

4. Create the delete sponsorship fund endpoint at DELETE `/sponsorshipfunds/:id`
The delete should delete only the sponsorship fund matching the specific sponsorship fund id in the database.

5. Create the get by id sponsorship fund endpoint at GET `/sponsorshipfunds/:id`
The get should get the sponsorship fund matching the specific sponsorship fund id in the database.

To test, please use an API Platform like Postman to assure that it works.

**Comment by ben-z** [comment]
Ditto https://github.com/WATonomous/wato_finance_system/issues/6#issuecomment-1245277601
