### ISSUE TITLE
Display basic table of all funding requests associated with a fund

### ISSUE THREAD

**Issue by victorzheng02** [WATonomous/wato_finance_system#20]
If you were to visit /claim/{SPONSORSHIP_FUND_ID}, there should be a table of all funding items associated with that sponsorship fund id. For each of the funding items, there should be a list of their corresponding personal purchases/uw finance purchases. It should essentially look like this table:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/36215359/194224925-841b6066-9a0f-425f-838d-ae029fa6c191.png">

No styling necessary for now

NOTE: Later on, we want {SPONSORSHIP_FUND_ID} to be the user friendly id from https://github.com/WATonomous/wato_finance_system/issues/10 once that is addressed.

**Comment by ansonjwhe** [comment]
Resolved by #49
