### ISSUE TITLE
Restrict login access to only WATO google accounts and check for groups

### ISSUE THREAD

**Issue by ansonjwhe** [WATonomous/wato_finance_system#23]
Currently users can login with any google account (including non-WATO accounts). We want to enforce that only users who have google accounts of the format xyz@watonomous.ca can login.

Additionally, we want to see if we can whitelist specific non-WATO accounts (i.e. our Finance Coordinator's uwaterloo email) so that we can authenticate specific individuals that should have access to our finance system

As a final task, investigate whether or not its possible to check for a users google group - we want to be able to see if given a user id, whether or not they're part of a given user google group. 
e.g: finance@watonomous.ca, team-captain@watonomous.ca. You can view your own groups here: https://groups.google.com/u/0/my-groups

**Comment by victorzheng02** [comment]
Partially done: issue is we are doing validation in the frontend currently. need to switch to backend somehow, want to avoid using firebase functions since they cost money.
