### ISSUE TITLE
create funding item endpoints

### ISSUE THREAD

**Issue by ansonjwhe** [WATonomous/wato_finance_system#3]
1. Create the create funding item endpoint at POST `/fundingitem`
The post request body should match the schema of FundingItem.model.js

2. Create the get all funding item endpoint at GET `/fundingitem`
The get should have no query parameters and return all the funding items

3. Create the edit funding item endpoint at PUT `/fundingitem/:id`
The put request body should match the schema of FundingItem.model.js with all fields optional. It should add or update any fields specified in the request body. All fields not specified in the request body should be touched.

4. Create the delete funding item endpoint at DELETE `/fundingitem/:id`
The delete should delete only the funding item matching the specific funding item id in the database.

5. Create the get by id funding item endpoint at GET `/fundingitem/:id`
The get should get the funding item matching the specific funding item id in the database.

To test, please use an API Platform like Postman to assure that it works.

**Comment by ben-z** [comment]
Ditto https://github.com/WATonomous/wato_finance_system/issues/6#issuecomment-1245277601
