### ISSUE TITLE
create personal purchase endpoints

### ISSUE THREAD

**Issue by ansonjwhe** [WATonomous/wato_finance_system#5]
1. Create the create personal purchase endpoint at POST `/personalpurchase`
The post request body should match the schema of PersonalPurchaseRequest.model.js

2. Create the get all personal purchase endpoint at GET `/personalpurchase`
The get should have no query parameters and return all the personal purchases

3. Create the edit personal purchase endpoint at PUT `/personalpurchase/:id`
The put request body should match the schema of PersonalPurchaseRequest.model.js with all fields optional. It should add or update any fields specified in the request body. All fields not specified in the request body should be touched.

4. Create the delete personal purchase endpoint at DELETE `/personalpurchase/:id`
The delete should delete only the personal purchase matching the specific personal purchase id in the database.

5. Create the get by id personal purchase endpoint at GET `/personalpurchase/:id`
The get should get the personal purchase matching the specific personal purchase id in the database.

To test, please use an API Platform like Postman to assure that it works.

**Comment by ben-z** [comment]
Ditto https://github.com/WATonomous/wato_finance_system/issues/6#issuecomment-1245277601
