### ISSUE TITLE
Improve getallchildren via populate method 

### ISSUE THREAD

**Issue by victorzheng02** [WATonomous/wato_finance_system#55]
getallchildren endpoint currently uses custom logic to turn id's into the objects that it is referencing. While this does work, the function can be simplified a lot and look cleaner via the populate method.

**Comment by ansonjwhe** [comment]
- #52 resolves this by ensuring that getAllChildren uses the fundingItem and sponsorshipFund getters with the aggregation pipeline to append dynamically generated fields. The populate method would bypass our custom aggregation and prevent the dynamic fields from being added.
