### ISSUE TITLE
create uw finance purchase endpoints

### ISSUE THREAD

**Issue by ansonjwhe** [WATonomous/wato_finance_system#6]
1. Create the create uw finance purchase endpoint at POST `/uwfinancepurchase`
The post request body should match the schema of UWFinancePurchaseRequest.model.js

2. Create the get all uw finance purchase endpoint at GET `/uwfinancepurchase`
The get should have no query parameters and return all the uw finance purchases

3. Create the edit uw finance purchase endpoint at PUT `/uwfinancepurchase/:id`
The put request body should match the schema of UWFinancePurchaseRequest.model.js with all fields optional. It should add or update any fields specified in the request body. All fields not specified in the request body should be touched.

4. Create the delete uw finance purchase endpoint at DELETE `/uwfinancepurchase/:id`
The delete should delete only the uw finance purchase matching the specific uw finance purchase id in the database.

5. Create the get by id uw finance purchase endpoint at GET `/uwfinancepurchase/:id`
The get should get the uw finance purchase matching the specific uw finance purchase id in the database.

To test, please use an API Platform like Postman to assure that it works.

**Comment by ben-z** [comment]
If we follow the REST guidelines we can simplify these endpoints:

```
POST /uwfinancepurchases
GET /uwfinancepurchases
GET /uwfinancepurchases/:id
PUT /uwfinancepurchases/:id
DELETE /uwfinancepurchases/:id
```

Note the plural form and how we encode actions into the request type.

[Here’s a good post about this](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/).

**Comment by ben-z** [comment]
This backend seems like a very standard CRUD app. We might want to consider auto-generating it. E.g. using https://github.com/daptin/daptin. This gives us the additional benefit of getting lots of tools for free, e.g. openAPI specs, sign up/login flow. All in all less grunt work and less code to maintain.

More options: https://news.ycombinator.com/item?id=22091012

**Comment by ben-z** [comment]
If we are feeling adventurous and want to eliminate even more grunt work, we can experiment with [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS?wprov=sfti1). I’ve never tried this but from what I’m reading, we can auto-generate pretty much the entire client side — no need to manually maintain forms!

**Comment by victorzheng02** [comment]
I'll talk to the other devs working on this, seems interesting!
