### ISSUE TITLE
Ticket Creation Form Validation

### ISSUE THREAD

**Issue by victorzheng02** [WATonomous/wato_finance_system#85]
~~For the create ticket modal, we want to validate that each field is properly validated and of the correct type. For example, semester should be a dropdown of Spring, Winter, Fall as opposed to a regular input field, purchase justification should be a textarea.~~

We want nice visual errors to show when certain restrictions aren't fit (such as entering a non-link into purchase URL should error and let the user know).

We also want an error toast to pop up if the create fails and to display the nature of the error if possible.

**Comment by ansonjwhe** [comment]
org and semester dropdown as well as textareas implemented in #90

**Comment by ansonjwhe** [comment]
all validation is already implemented, error toast logic duplicates #84
